name: MLOps CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Use Python 3.12 (same as your local)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train model
      run: python src/train.py

    - name: Run data drift check
      run: python monitoring/data_drift.py

    - name: Verify model exists
      run: |
        if [ ! -f models/model.pkl ]; then
          echo "Model not created!"
          exit 1
        fi